.Dd December 5, 2023
.Dt ZXCV 1
.Os
.Sh NAME
.Nm zxcv
.Nd z xssential content viewer
.Sh SYNOPSIS
.Nm zxcv
.Op Fl f Ar file
.Ar url
.Sh DESCRIPTION
The
.Nm
utility displays the essential content of a URL via a local command (e.g.
.Xr less 1
.Xr mupdf 1
).
The options are as follows:
.Bl -tag -width Ds
.It Fl f Ar file
Specify a configuration file.
.El
.Sh AUTHORS
.An Matthew Martin Aq Mt phy1729@gmail.com
