.Dd December 2, 2023
.Dt ZXCV 1
.Os
.Sh NAME
.Nm zxcv
.Nd z xssential content viewer
.Sh SYNOPSIS
.Nm zxcv
.Fl c
.Nm zxcv
.Ar url
.Sh DESCRIPTION
The
.Nm
utility displays the essential content of a URL via a local command (e.g.
.Xr less 1
.Xr mupdf 1
).
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Use the URL in the clipboard.
.El
.Sh AUTHORS
.An Matthew Martin Aq Mt phy1729@gmail.com
